#!/usr/bin/env bash
set -euo pipefail

# Config file

config_file="conf/config.yaml"

# Ensure the environment is activated

REQUIRED_ENV="code-as-data"

if [[ $(basename "${CONDA_PREFIX}") != "${REQUIRED_ENV}" ]]; then
  echo "Retry with CONDA env '${REQUIRED_ENV}'" >&2
  exit 1
fi

# Ensure the results directories are set up

for key in "results_dir" "pkg_results_dir" "repo_dir"; do
  dir="$(cat "${config_file}" | shyaml get-value "${key}")"
  if [[ ! -d ${dir} ]]; then mkdir -p ${dir}; fi
done

# Ensure the R environment is set up

Rscript -e "renv::restore()"
