---
title: "Experiments for Code-as-Data"
author: "Russell Hyde"
date: "19 October 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
```

```{r}
pkgs <- c(
  "dplyr",
  "forcats",
  "ggplot2",
  "igraph",
  "magrittr",
  "readr"
)

for (pkg in pkgs) {
  suppressPackageStartupMessages(
    library(pkg, character.only = TRUE)
  )
}
```

```{r}
dirs <- list(
  results = here("results")
)
```

```{r}
# Files for cross-package comparison
files <- list(
  cloc = file.path(dirs[["results"]], "dev-pkg-cloc.tsv"),
  gitsum = file.path(dirs[["results"]], "dev-pkg-gitsum.tsv")
)
```

# Dataset

```{r}
gitsum <- readr::read_tsv(
  files[["gitsum"]],
  col_types = readr::cols()
) %>%
  # for consistency with cloc 'filename' column
  rename(filename = changed_file)

head(gitsum)
```

```{r}
cloc <- list()

cloc$by_file <- readr::read_tsv(
  files[["cloc"]],
  col_types = readr::cols()
) %>%
  # convert "some/path/to/R/filename.R" to "R/filename.R" to match the gitsum
  # filenames
  mutate(
    filename = gsub(".*\\/(R\\/.*)$", "\\1", x = filename)
  )

cloc$by_pkg <- cloc[["by_file"]] %>%
  group_by(package) %>%
  summarise_if(is.numeric, sum)
```

```{r}
head(cloc$by_file)
```

```{r}
head(cloc$by_pkg)
```

```{r}
# Obtain the total number of commits, contributors and lines-of-code for each
# package
pkg_summary <- gitsum %>%
  group_by(package) %>%
  summarise(
    n_commits = n_distinct(hash),
    n_contributors = n_distinct(author_email)
  ) %>%
  inner_join(
    cloc$by_pkg,
    by = "package"
  )

head(pkg_summary[, 1:4])
```

# Which package has the most commits / contributors / lines-of-code?

```{r}
pkg_summary %>% arrange(desc(n_commits))
pkg_summary %>% arrange(desc(n_contributors))
pkg_summary %>% arrange(desc(loc))
```

```{r, message=FALSE}
pkg_summary %>%
  ggplot(aes(x = loc)) +
  geom_histogram() +
  scale_x_log10() +
  xlab("Lines of code") +
  ggtitle(label = "The R packages differ greatly in size")
```

```{r}
p <- pkg_summary %>%
  ggplot(aes(label = package)) +
  scale_x_log10() +
  scale_y_log10()

p + geom_text(aes(x = loc, y = n_commits))
```

```{r}
p + geom_text(aes(x = loc, y = jitter(n_contributors)))
```

```{r}
p +
  geom_text(aes(x = n_commits, y = jitter(n_contributors), alpha = loc)) +
  xlab("Number of Commits") +
  ylab("Number of Contributors (jittered)") +
  ggtitle("Contributions / Contributor numbers differ greatly") +
  scale_alpha_continuous(trans = "log10", name = "Lines of code")
```

# Analysis of {lintr}

## Change frequency for the files

```{r}
summarise_commits_by_file <- function(commits, cloc_by_file) {
  commits %>%
    group_by(package, filename) %>%
    summarise(n_changes = n()) %>%
    inner_join(
      cloc_by_file,
      by = c("package", "filename")
    )
}
```

```{r}
compute_comodification <- function(x) {
  stopifnot(all(c("package", "filename", "hash") %in% colnames(x)))

  x %>%
    dplyr::select(package, filename, hash) %>%
    # Determine all pairs of files that are modified within a given commit:
    inner_join(x = ., y = ., by = c("hash", "package")) %>%
    # Count the number of commits where a given pair of files is co-modified:
    group_by(package, filename.x, filename.y) %>%
    summarise(n_commits = n()) %>%
    # In what fraction of the commits where file X is modified, is file Y also
    # modified?
    group_by(package, filename.x) %>%
    mutate(
      fraction_comodified = n_commits / max(n_commits)
    )
}
```

```{r}
plot_file_commits_by_author <- function(commits) {
  commits %>%
    ggplot(
      aes(
        x = fct_infreq(filename),
        fill = fct_lump(fct_infreq(author_name), n = 7)
      )
    ) +
    geom_bar() +
    xlab("Filename") +
    ylab("Number of Commits") +
    scale_x_discrete(breaks = NULL) +
    scale_fill_discrete(name = "Author")
}
```

```{r}
lintr <- list()
lintr$commits <- filter(gitsum, package == "lintr")
lintr$cloc <- filter(cloc$by_pkg, package == "lintr")
lintr$by_file <- summarise_commits_by_file(lintr$commits, cloc$by_file)
lintr$comod <- compute_comodification(lintr[["commits"]])
```

```{r}
lintr$by_file %>%
  ggplot(
    aes(
      x = fct_reorder(filename, n_changes, .desc = TRUE),
      y = n_changes
    )
  ) +
  geom_bar(stat = "identity") +
  xlab("Filename") +
  scale_x_discrete(breaks = NULL)
```

```{r}
lintr$by_file %>%
  ggplot(
    aes(
      x = fct_reorder(filename, n_changes, .desc = TRUE),
      y = loc
    )
  ) +
  geom_bar(stat = "identity") +
  xlab("Filename") +
  scale_x_discrete(breaks = NULL)
```

```{r}
plot_file_commits_by_author(lintr$commits)
```

```{r}
p_loc_vs_commits <- lintr$by_file %>%
  ggplot(
    aes(
      x = loc,
      y = n_changes,
      label = filename
    )
  ) +
  geom_text() +
  scale_x_log10() +
  scale_y_log10() +
  xlab("Lines of Code") +
  ylab("Number of Commits")

p_loc_vs_commits
```

## Change correlations between files

```{r}
head(lintr$comod)
```

<!-- TODO: tidygraph of the comodification data -->

# Do the same but for shiny

```{r}
shiny <- list()
shiny$commits <- filter(gitsum, package == "shiny")
shiny$cloc <- filter(cloc$by_pkg, package == "shiny")
shiny$by_file <- summarise_commits_by_file(shiny$commits, cloc$by_file)
shiny$comod <- compute_comodification(shiny[["commits"]])
```

```{r}
plot_file_commits_by_author(shiny$commits)
```

```{r}
p_loc_vs_commits %+% shiny$by_file
```

```{r}
edges <- shiny$comod[, c("filename.x", "filename.y", "n_commits", "fraction_comodified")] %>%
  filter(filename.x != filename.y & filename.x %in% shiny$by_file$filename) %>%
  filter(n_commits > 5 & fraction_comodified > 0.5)

vertices <- shiny$by_file[-1] %>%
  filter(filename %in% edges$filename.x | filename %in% edges$filename.y)

g <- igraph::graph_from_data_frame(edges, vertices = vertices)
```

```{r}
plot(g, color = 5 * vertices$loc, layout = layout_with_fr)
```

```{r}
filter(edges, filename.x == "R/timer.R")
```
